//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamThiThuySang
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        public string MaKhoa { get; set; }
        public string TenKhoa { get; set; }
    }
}
