//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamThiThuySang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhamThiThuySang1Entities : DbContext
    {
        public PhamThiThuySang1Entities()
            : base("name=PhamThiThuySang1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOANPHI> DOANPHIs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<KHOAHOC> KHOAHOCs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<LOP_SINHVIEN> LOP_SINHVIEN { get; set; }
        public virtual DbSet<SINHVIEN_DOANPHIHOI> SINHVIEN_DOANPHIHOI { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    }
}
