//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamThiThuySang16T
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TTSV
    {
        public int masv { get; set; }
        public string tensv { get; set; }
        public string diachi { get; set; }
        public Nullable<int> makhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
